= Alcyone: A development history
Joseph B. Ottinger <joeo@enigmastation.com>
:toc:
:icons:

== Purpose

The Alcyone is a home-built MIDI controller, using the Raspberry Pi as 
a central controlling component. 

The Alcyone is an ongoing design, so this document
will address not only existing components, but will also address potential
future enhancements. Rationales for architectural choices will be offered
where appropriate, with the understanding that some choices were made 
"just because," out of ignorance, necessity, or mere personal preference.

=== Rationale

The Alcyone was designed with two primary purposes in mind.

One purpose was almost purely selfish; I wanted a MIDI controller in
the form of bass pedals. Building a foot pedal would be far less expensive
than purchasing a Moog Taurus 3 (a full analog synthesizer in 
a footpedal form factor) or even a Roland PK-6 (a simple footpedal controller,
at roughly $900 USD).

NOTE: The Moog Taurus 2 (not the Taurus 3) was the original inspiration
for the Alcyone, and inspired its name. However, the PK-6 is more of
a direct equivalent to the Alcyone. I can't for the life of me figure
out what I'd have named the device if I was trying to derive the name
from "PK-6."

The other purpose was the actual linchpin for the design. I wanted to
figure out what actually went into musical instrument design, such that
I might be able to design other musical instruments. 

I also wanted to be able to tell _others_ how the Alcyone was designed,
such that _they_ might be able to not only build their own Alcyone, if
that was what they desired, and they might also be able to build their
_own_ designs (and share them with me, in kind.)

=== The Name

"Alcyone" is pronounced "al-SEE-on-ee." The _correct_ pronunciation of
the word is "al-SIGH-on-ee," but I prefer my pronunciation because it's
easier... as you'll see from this explanation.

"Alcyone" as a name was derived from a series of steps starting with the Moog
Taurus.

The Taurus was originally designed as a part of a synthesizer ensemble 
from Moog, called the "Constellation." The Taurus was the bass pedal of the
ensemble; the other parts were the "Lyra" and the "Apollo." The Lyra was
never built; the Apollo's design apparently found its way into the PolyMoog.

The Taurus, however, became very popular, through its use in bands 
like Rush, Genesis, and others.

"Alcyone" as a name followed this linear thought:

. Taurus is a constellation, and the Taurus synthesizer was part of an 
ensemble called the "Constellation."
. The Taurus constellation's brightest star is Aldebaran, but "Aldebaran"
is unwieldy as a name. This is fairly ironic, since "Alcyone" isn't exactly
trivial to say either.
. Taurus' next-brightest star is Tau, but Tau is the name of another
musical instrument, from Eigenharp.
. Taurus' _next_ brightest star is Alcyone, one of the Pleiades; Alcyone is
the name of a Greek tragic heroine, so there's some measure of appeal
for mythology's sake as well.

The warped pronunciation came from "halcyon," which is a variant of 
Alcyone's name; "halcyon" uses the "ee" form of the "y," and it's easier
for me to pronounce, to boot.

=== Scope

The Alcyone is "merely" a MIDI controller; it does not generate any
sound in and of itself, although this would be a welcomed capability. The
Raspberry Pi's audio output is only 11 bits, which is better than, say, 
a Nintendo DS or some ancient digital synthesizers, but is far inferior
to CD quality, and is nowhere near what I would like for actual
audio creation.

== Terms

=== MIDI

MIDI stands for "Musical Instrument Digital Interface," and is an 
industry-standard protocol for electronic instruments. It is based on 
three types of events (note events, control events, and global events)
and uses a serial connection at 31250 baud.

== Architecture

=== Hardware

The Alcyone uses a very simple internal electronic design. 

The pedals themselves are a 13-note chord, salvaged from an old
Lowrey organ, purchased over EBay. They rely on a rocker switch that
pulls a spring across a circuit to close it.

As best I can tell, in the Lowrey design the pedals convert the 
circuit to a CV/Gate signal, which was a standard before MIDI was
created. However, CV/Gate was never specified; different manufacturers
use different implementations.

CV/Gate _normally_ converts to a voltage; the first note might be +1v, 
the second note +2v, and so forth. However, this is a convention and
not a standard; plus, the Raspberry Pi has neither analog inputs nor
the capability to handle +13v.

I don't _think_ the Lowrey pedals were monophonic, so it's possible
that it used a digital output, but I don't know for sure. 

Given my limited analytical capabilities, it was simpler to use as
little of the existing mechanism as possible, which meant relying solely
on the rocker switch, and wiring my own digital I/O.

As the Pi only has a limited number of GPIO pins, I wired the circuits
for the rocker switches to a set of I2C chips. These use a serial
protocol to map GPIO pins; the MCP23008 offers eight individually-addressible 
GPIO pins, and the MCP23017 offers sixteen.

The I2C chips can be wired such that seven of them are on a single serial
connection; thus, if you use seven MCP23008 chips in a series, you have 56
uniquely addressable pins; with the MCP23017, you could have 112. There are
likely to be other I2C chips available, and you don't have to have a
homogenous chain.

The physical electronic circuit is, thus, very simple. Three MCP23008s, 
in series, with two of them dedicated to pedal input and one driving three
LEDs for runtime status.

The pedals are connected to power (+5v) and wired to the MCP23008s; the
digital inputs are also connected to pull-down resistors to clear out
digital noise.

The Raspberry Pi is connected to the I2C series and also to a Din5 connector
(the industry standard for MIDI connections). The Din5 is mounted on a Sparkfun
MIDI breakout kit, mostly chosen for availability and ease of use.

A powered USB hub is also part of the hardware installation; the hub
has one device installed, a wireless networking dongle. The powered hub
is necessary because the Raspberry Pi does not carry enough current
to reliably power most wireless dongles.

==== Why Wireless TCP/IP?

The wireless networking is part of a software choice made fairly early
in the implementation cycle.

More details will be discussed in the section on the Alcyone
software, but initial external control relied on the Raspberry Pi's
onboard ethernet connection. 

This implies the requirement for networking infrastructure. However,
one facet of the Alcyone's projected use was stage work - and on
some of the stages available to me, networking is very spotty if 
existent at all.

The simplest solution involves the Alcyone serving as its 
own wireless access point, then, meaning that it provides its own
networking infrastructure.

An alternative would be to avoid TCP/IP altogether. Bluetooth is 
another messaging protocol, one designed very much for device-to-device
communications, particularly for short messages. Bluetooth devices
can also be designed for very low power usage.

== References
