# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jottinge/work/alcyone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jottinge/work/alcyone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jottinge/work/alcyone/CMakeFiles /home/jottinge/work/alcyone/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jottinge/work/alcyone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named alcyone

# Build rule for target.
alcyone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alcyone
.PHONY : alcyone

# fast build rule for target.
alcyone/fast:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/build
.PHONY : alcyone/fast

alcyone.o: alcyone.cpp.o
.PHONY : alcyone.o

# target to build an object file
alcyone.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/alcyone.cpp.o
.PHONY : alcyone.cpp.o

alcyone.i: alcyone.cpp.i
.PHONY : alcyone.i

# target to preprocess a source file
alcyone.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/alcyone.cpp.i
.PHONY : alcyone.cpp.i

alcyone.s: alcyone.cpp.s
.PHONY : alcyone.s

# target to generate assembly for a file
alcyone.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/alcyone.cpp.s
.PHONY : alcyone.cpp.s

alcyoneServer.o: alcyoneServer.cpp.o
.PHONY : alcyoneServer.o

# target to build an object file
alcyoneServer.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/alcyoneServer.cpp.o
.PHONY : alcyoneServer.cpp.o

alcyoneServer.i: alcyoneServer.cpp.i
.PHONY : alcyoneServer.i

# target to preprocess a source file
alcyoneServer.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/alcyoneServer.cpp.i
.PHONY : alcyoneServer.cpp.i

alcyoneServer.s: alcyoneServer.cpp.s
.PHONY : alcyoneServer.s

# target to generate assembly for a file
alcyoneServer.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/alcyoneServer.cpp.s
.PHONY : alcyoneServer.cpp.s

debounce.o: debounce.cpp.o
.PHONY : debounce.o

# target to build an object file
debounce.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/debounce.cpp.o
.PHONY : debounce.cpp.o

debounce.i: debounce.cpp.i
.PHONY : debounce.i

# target to preprocess a source file
debounce.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/debounce.cpp.i
.PHONY : debounce.cpp.i

debounce.s: debounce.cpp.s
.PHONY : debounce.s

# target to generate assembly for a file
debounce.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/debounce.cpp.s
.PHONY : debounce.cpp.s

flare.o: flare.cpp.o
.PHONY : flare.o

# target to build an object file
flare.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/flare.cpp.o
.PHONY : flare.cpp.o

flare.i: flare.cpp.i
.PHONY : flare.i

# target to preprocess a source file
flare.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/flare.cpp.i
.PHONY : flare.cpp.i

flare.s: flare.cpp.s
.PHONY : flare.s

# target to generate assembly for a file
flare.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/flare.cpp.s
.PHONY : flare.cpp.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/log.cpp.s
.PHONY : log.cpp.s

mcp23008.o: mcp23008.cpp.o
.PHONY : mcp23008.o

# target to build an object file
mcp23008.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/mcp23008.cpp.o
.PHONY : mcp23008.cpp.o

mcp23008.i: mcp23008.cpp.i
.PHONY : mcp23008.i

# target to preprocess a source file
mcp23008.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/mcp23008.cpp.i
.PHONY : mcp23008.cpp.i

mcp23008.s: mcp23008.cpp.s
.PHONY : mcp23008.s

# target to generate assembly for a file
mcp23008.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/mcp23008.cpp.s
.PHONY : mcp23008.cpp.s

midi.o: midi.cpp.o
.PHONY : midi.o

# target to build an object file
midi.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/midi.cpp.o
.PHONY : midi.cpp.o

midi.i: midi.cpp.i
.PHONY : midi.i

# target to preprocess a source file
midi.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/midi.cpp.i
.PHONY : midi.cpp.i

midi.s: midi.cpp.s
.PHONY : midi.s

# target to generate assembly for a file
midi.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/midi.cpp.s
.PHONY : midi.cpp.s

serialdevice.o: serialdevice.cpp.o
.PHONY : serialdevice.o

# target to build an object file
serialdevice.cpp.o:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/serialdevice.cpp.o
.PHONY : serialdevice.cpp.o

serialdevice.i: serialdevice.cpp.i
.PHONY : serialdevice.i

# target to preprocess a source file
serialdevice.cpp.i:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/serialdevice.cpp.i
.PHONY : serialdevice.cpp.i

serialdevice.s: serialdevice.cpp.s
.PHONY : serialdevice.s

# target to generate assembly for a file
serialdevice.cpp.s:
	$(MAKE) -f CMakeFiles/alcyone.dir/build.make CMakeFiles/alcyone.dir/serialdevice.cpp.s
.PHONY : serialdevice.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... alcyone"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alcyone.o"
	@echo "... alcyone.i"
	@echo "... alcyone.s"
	@echo "... alcyoneServer.o"
	@echo "... alcyoneServer.i"
	@echo "... alcyoneServer.s"
	@echo "... debounce.o"
	@echo "... debounce.i"
	@echo "... debounce.s"
	@echo "... flare.o"
	@echo "... flare.i"
	@echo "... flare.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... mcp23008.o"
	@echo "... mcp23008.i"
	@echo "... mcp23008.s"
	@echo "... midi.o"
	@echo "... midi.i"
	@echo "... midi.s"
	@echo "... serialdevice.o"
	@echo "... serialdevice.i"
	@echo "... serialdevice.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

